#!/usr/bin/env tsx
/**
 * gen-sigmap: Extracts type/interface/function signatures from the codebase
 * (stripping implementation bodies) and writes a compact structural skeleton
 * to .relay/sigmap.md for use as a token-efficient source-snapshot alternative.
 *
 * Run: pnpm sigmap
 */
// typescript@7 (native) no longer exports the classic compiler API from the
// package root, so signature extraction parses with a pinned TS5 alias.
import * as ts from "typescript5";
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const OUT_PATH = join(ROOT, ".relay", "sigmap.md");

function findTsFiles(dir: string): string[] {
  const results: string[] = [];
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    if (entry.name === "dist" || entry.name === "node_modules") continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findTsFiles(full));
    } else if (
      entry.isFile() &&
      entry.name.endsWith(".ts") &&
      !entry.name.endsWith(".test.ts") &&
      !entry.name.endsWith(".d.ts")
    ) {
      results.push(full);
    }
  }
  return results;
}

function extractSignatures(filePath: string, source: string): string[] {
  const sf = ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true);
  const sigs: string[] = [];

  for (const node of sf.statements) {
    if (
      ts.isInterfaceDeclaration(node) ||
      ts.isTypeAliasDeclaration(node) ||
      ts.isEnumDeclaration(node)
    ) {
      sigs.push(node.getText(sf).trim());
    } else if (ts.isFunctionDeclaration(node)) {
      const bodyStart = node.body ? node.body.getStart(sf) : null;
      const sig = bodyStart !== null
        ? source.slice(node.getStart(sf), bodyStart).trimEnd().replace(/\s*\{$/, "")
        : node.getText(sf).trim();
      sigs.push(`${sig} {}`);
    } else if (ts.isVariableStatement(node)) {
      const text = node.getText(sf).trim();
      const hasArrow = text.includes("=>");
      const hasFunc = /\bfunction\b/.test(text);
      if (hasArrow || hasFunc) {
        const arrowIdx = text.indexOf("=>");
        if (hasArrow && arrowIdx > -1) {
          const afterArrow = text.slice(arrowIdx + 2).trimStart();
          sigs.push(afterArrow.startsWith("{")
            ? text.slice(0, arrowIdx + 2).trimEnd() + " {}"
            : text);
        } else {
          sigs.push(text);
        }
      } else {
        sigs.push(text);
      }
    } else if (ts.isClassDeclaration(node)) {
      const name = node.name ? ` ${node.name.text}` : "";
      const heritage = node.heritageClauses
        ? " " + node.heritageClauses.map((h) => h.getText(sf)).join(" ")
        : "";
      const memberSigs = node.members.map((m) => {
        if (
          ts.isMethodDeclaration(m) ||
          ts.isConstructorDeclaration(m) ||
          ts.isGetAccessorDeclaration(m) ||
          ts.isSetAccessorDeclaration(m)
        ) {
          const mb = (m as ts.MethodDeclaration).body;
          const end = mb ? mb.getStart(sf) : m.getEnd();
          const sig = source.slice(m.getStart(sf), end).trimEnd().replace(/\s*\{$/, "");
          return `  ${sig} {}`;
        }
        return `  ${m.getText(sf).trim()}`;
      });
      sigs.push(`class${name}${heritage} {\n${memberSigs.join("\n")}\n}`);
    } else if (ts.isExportDeclaration(node)) {
      sigs.push(node.getText(sf).trim());
    }
  }

  return sigs.filter(Boolean);
}

const packagesDir = join(ROOT, "packages");
let files: string[] = [];
try {
  const pkgs = readdirSync(packagesDir, { withFileTypes: true });
  for (const pkg of pkgs) {
    if (pkg.isDirectory()) {
      files.push(...findTsFiles(join(packagesDir, pkg.name, "src")));
    }
  }
} catch {
  process.stderr.write(`Error: could not read packages directory at ${packagesDir}\n`);
  process.exit(1);
}
files.sort();

const sections: string[] = [];
for (const file of files) {
  const rel = relative(ROOT, file);
  const source = readFileSync(file, "utf8");
  const sigs = extractSignatures(file, source);
  if (sigs.length > 0) {
    sections.push(`### ${rel}\n\`\`\`typescript\n${sigs.join("\n\n")}\n\`\`\``);
  }
}

mkdirSync(join(ROOT, ".relay"), { recursive: true });
const header = `# Codebase Signature Map\n_Generated by \`pnpm sigmap\`. Do not edit manually._\n\n`;
const output = header + sections.join("\n\n");
writeFileSync(OUT_PATH, output, "utf8");

const kb = (output.length / 1024).toFixed(1);
console.log(`✓ sigmap: ${sections.length} modules → ${OUT_PATH} (${kb} KB)`);
